ALTER TABLE productos
  ADD COLUMN descripcion VARCHAR(255) NULL AFTER nombre;

ALTER TABLE productos
  ADD COLUMN createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE productos
  ADD COLUMN updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
